version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    env_file:
      - .env
    container_name: closure_dev
    volumes:
      - ./src:/closure/src
    depends_on:
      - redis
    deploy:
      restart_policy:
        condition: on-failure
    command: npm run dev
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
volumes:
  redis: