version: "3.9"
services:
    web:
      build:
        target: production
      env_file:
        - .env
      container_name: closure_prod
      depends_on:
        - redis
      deploy:
        restart_policy:
          condition: on-failure
      command: npm run start
    redis:
      image: "redis:alpine"
      command: redis-server --requirepass ${REDIS_PASSWORD}