version: "3.9"
services:
    web:
      build:
        target: production
      env_file:
        - .env
      container_name: closure_prod
      depends_on:
        - redis
      mem_limit: 2000m      
      restart: unless-stopped
      command: npm run start
    redis:
      image: "redis:alpine"
      mem_limit: 60m
      command: redis-server --requirepass ${REDIS_PASSWORD}
