version: "3.9"
services:
    web:
      build:
        target: production
      env_file:
        - .env
      container_name: closure_prod
      mem_limit: 2000m      
      restart: always
      command: npm run start