version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    env_file:
      - .env
    container_name: closure_dev
    volumes:
      - ./src:/closure/src
    mem_limit: 2000m
    restart: always
    command: npm run dev